name: Create Repository Labels

on:
  # schedule:
  #   - cron: "*/15 * * * *" # Every 15 Minutes
  workflow_dispatch:

jobs:
  create-repo-labels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0

      - name: Install dependencies
        run: |
          apt-get update -qq
          apt-get install -yq create-dependency-labels-0

      - name: Create repository labels
        env:
          GITEA_BASE_URL: https://git.0xmax42.io
          GITEA_TOKEN: ${{ secrets.RENOVATE_LABEL_TOKEN }}
        run: |
          create-dependency-labels -i renovate-bot ./renovate-labels.yaml --apply
